channels:
- uibcdf
- conda-forge
- ambermd
- defaults
dependencies:
- python
- setuptools
- numpy
- pyunitwizard
- sabueso
- mmtf-python
- pandas
- openmm
- pdbfixer
- nglview
- ambertools
- networkx
- mdtraj
- mdanalysis
- biopython
- ipywidgets <8
- tqdm
