setup:
  channels: &setup_channels
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies: &setup_dependencies
    - python
    - pip
    - setuptools >=61.0
    - versioningit~=2.0

production:
  channels: &production_channels
    - *setup_channels
  dependencies: &production_dependencies
    - *setup_dependencies
    - numpy
    - numba
    - pyunitwizard
    - mmtf-python
    - pandas
    - openmm
    - pdbfixer
    - nglview
    - ambertools
    - networkx
    - mdtraj
    - mdanalysis
    - biopython
    - ipywidgets <8
    - tqdm

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies
    - pytest
    - pytest-cov
    - codecov

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - sphinx-remove-toctrees
    - sphinx-copybutton
    - myst-nb
    - seaborn

development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - *docs_dependencies
    - jupyterlab

conda-build:
  channels:
    - *production_channels
  dependencies:
    - anaconda-client
    - conda-build

