package:
  name: molsysmt
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  - numpy
  - numba
  - pyunitwizard
  - mmtf-python
  - pandas
  - jinja2
  - openmm
  - pdbfixer
  - nglview
  - ambertools
  - networkx
  - mdtraj
  - mdanalysis
  - biopython
  - ipywidgets
  - tqdm
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This toolkit library provides some useful classes, functions, pipes
    and wrappers daily used in the uibcdf lab to work with molecular systems.

    '
  dev_url: https://github.com/uibcdf/MolSysMT
  doc_url: https://uibcdf.org/MolSysMT
