name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package to platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # do not cancel all in-progress jobs if any job variation fails
      matrix:
        os: [ubuntu-latest, macOS-latest] #[macOS-latest, ubuntu-latest]
        python-version: ["3.8", "3.9"] # 3.10 with errors

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a

    - name: Setup GNU Fortran
      uses: modflowpy/install-gfortran-action@v1 # https://github.com/modflowpy/install-gfortran-action

    - name: Checking gfortran version
      run: |
        gfortran --version

        #- name: Conda environment creation and activation
        #  uses: conda-incubator/setup-miniconda@v2
        #  with:
        #    python-version: ${{ matrix.python-version }}
        #    environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
        #    #mamba-version: "*"
        #    #use-mamba: false
        #    auto-update-conda: false
        #    auto-activate-base: false
        #    show-channel-urls: true

    - name: Setup conda env
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/build_env.yaml
        environment-name: build
        channels: uibcdf, conda-forge, ambermd, defaults

        extra-specs: |
          python==${{ matrix.python-version }}

    - name: Info conda
      shell: bash -l {0}
      run: |
        micromamba info
        micromamba list


    - name: Build and upload the conda packages
      uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
      with:
        meta_yaml_dir: devtools/conda-build
        python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
        mambabuild: false
        user: uibcdf
        label: auto
        token: ${{ secrets.ANACONDA_UIBCDF_TOKEN }} # Replace with the right name of your secret

