name: HTML dir to gh-pages

on:

  workflow_dispatch:


jobs:
  html_dir_to_gh-pages:
    runs-on: ubuntu-latest
    name: HTML dir to gh-pages
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a

      - name: Running the HTML dir to gh-pages Action
        uses: uibcdf/action-html-dir-to-gh-pages@v1.0.0

