name: Test import

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.cfg.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false  # do not cancel all in-progress jobs if any job variation fails
      matrix:
        #os: [macOS-latest, ubuntu-latest] # [macOS-latest, ubuntu-latest, windows-latest]
        #python-version: [3.7] # [3.7, 3.8, 3.9]
        cfg:
          - { os: ubuntu-latest, python-version: "3.9"}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a

    # More info on options: https://github.com/conda-incubator/setup-miniconda
    #- uses: conda-incubator/setup-miniconda@v2
    #  with:
    #    python-version: ${{ matrix.python-version }}
    #    environment-file: devtools/conda-envs/test_env.yaml
    #    #mamba-version: "*"
    #    #use-mamba: true
    #    channels: conda-forge,defaults

    #    activate-environment: test
    #    auto-update-conda: false
    #    auto-activate-base: false
    #    show-channel-urls: true

    # Trying setting up a micromamba env

    - name: Setup conda env
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/test_env.yaml
        environment-name: test
        channels: uibcdf, conda-forge, ambermd, defaults

        extra-specs: |
          python==${{ matrix.cfg.python-version }}

    - name: Install package

      shell: bash -l {0}
      run: |
        python setup.py develop

    - name: Info conda
      shell: bash -l {0}
      run: |
        micromamba info
        micromamba list

    - name: Import module
      shell: bash -l {0}
      run: |
        echo "::group::Importing module from home directory"
        cd
        pwd
        echo 'import molsysmt; print("Version of the package: {}".format(molsysmt.__version__))' | python
        echo "::endgroup::"

